zones:
  zones:
  - id: seat_1
    bbox:
    - 16
    - 330
    - 383
    - 585
  - id: seat_2
    bbox:
    - 144
    - 228
    - 428
    - 447
  - id: seat_3
    bbox:
    - 414
    - 417
    - 773
    - 694
  - id: seat_4
    bbox:
    - 624
    - 174
    - 927
    - 413
  - id: seat_5
    bbox:
    - 938
    - 362
    - 1237
    - 683
  - id: seat_6
    bbox:
    - 434
    - 164
    - 714
    - 399
students:
- id: s1
  zone_id: seat_1
- id: s2
  zone_id: seat_2
- id: s3
  zone_id: seat_3
- id: s4
  zone_id: seat_4
- id: s5
  zone_id: seat_5
- id: s6
  zone_id: seat_6
