zones:
  zones:
    - id: seat_1
      bbox: [1.18, 8.33, 5.05, 12.0]
    - id: seat_2
      bbox: [3.18, 6.07, 5.75, 8.94]
    - id: seat_3
      bbox: [7.4, 10.26, 11.14, 14.42]
    - id: seat_4
      bbox: [10.68, 4.86, 13.55, 8.18]
    - id: seat_5
      bbox: [15.59, 9.05, 18.39, 14.18]
    - id: seat_6
      bbox: [7.72, 4.64, 10.22, 7.86]

students:
  - id: s1
    zone_id: seat_1
  - id: s2
    zone_id: seat_2
  - id: s3
    zone_id: seat_3
  - id: s4
    zone_id: seat_4
  - id: s5
    zone_id: seat_5
  - id: s6
    zone_id: seat_6
