zones:
  zones:
  - id: seat_1
    bbox:
    - 0
    - 290
    - 437
    - 625
  - id: seat_2
    bbox:
    - 100
    - 193
    - 472
    - 482
  - id: seat_3
    bbox:
    - 361
    - 374
    - 826
    - 719
  - id: seat_4
    bbox:
    - 578
    - 136
    - 973
    - 451
  - id: seat_5
    bbox:
    - 893
    - 314
    - 1279
    - 719
  - id: seat_6
    bbox:
    - 391
    - 127
    - 757
    - 436
students:
- id: s1
  zone_id: seat_1
- id: s2
  zone_id: seat_2
- id: s3
  zone_id: seat_3
- id: s4
  zone_id: seat_4
- id: s5
  zone_id: seat_5
- id: s6
  zone_id: seat_6
