meta:
  source: data/raw/SPU_DEMO.mp4
  width: 3840
  height: 2160
  zones: 8
zones:
- id: seat_1
  bbox:
  - 96
  - 1061
  - 479
  - 1606
- id: seat_2
  bbox:
  - 1490
  - 1216
  - 1906
  - 1624
- id: seat_3
  bbox:
  - 3311
  - 995
  - 3821
  - 1626
- id: seat_4
  bbox:
  - 571
  - 715
  - 1015
  - 1022
- id: seat_5
  bbox:
  - 1632
  - 479
  - 1835
  - 782
- id: seat_6
  bbox:
  - 2940
  - 678
  - 3255
  - 1105
- id: seat_7
  bbox:
  - 1814
  - 335
  - 2057
  - 529
- id: seat_8
  bbox:
  - 2691
  - 488
  - 2970
  - 738
